apiVersion: apps/v1
kind: Deployment
metadata:
  name: mycourt
  labels:
    app: mycourt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mycourt
  template:
    metadata:
      labels:
        app: mycourt
    spec:
      containers:
        - name: mycourt
          image: user01acr1.azurecr.io/mycourt:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
          env:
          - name: PROFILE
            valueFrom:
              configMapKeyRef:
                name: profile-cm
                key: profile 